### ISSUE TITLE
How do I get a view the style for the view of earth from space like google earth and I just zoom in from there and Hybrid views whats the name of it the code on vs?

### ISSUE THREAD

**Issue by luke827** [rbrundritt/SimpleUwpAzureMaps#4]
![Screenshot (628)](https://github.com/user-attachments/assets/771698dd-5d83-4b90-b6b5-40a3d6c7f86c)
![Screenshot (629)](https://github.com/user-attachments/assets/8746d375-29ca-4d17-8981-49efd4ce8295)

**Comment by rbrundritt** [comment]
This is ridiculous. There are a ton of ways for you to figure this out easily and instead you have to waste my time. I'm done with you. Don't use Azure Maps, go figure something out for yourself rather than getting others to do all the work for you and then you trying to sell their samples and demos to unsuspecting people.
